// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using NoticiasAdmin.Models;

namespace NoticiasAdmin.Data;

public partial class NoticiasDBContext : DbContext
{
    public NoticiasDBContext(DbContextOptions<NoticiasDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Categoria> Categorias { get; set; }

    public virtual DbSet<Noticia> Noticias { get; set; }

    public virtual DbSet<Paise> Paises { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Categoria>(entity =>
        {
            entity.HasKey(e => e.CategoriaId).HasName("PK__Categori__F353C1E5C289160C");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion).HasMaxLength(500);
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Noticia>(entity =>
        {
            entity.HasKey(e => e.NoticiaId).HasName("PK__Noticias__F33000CF12370340");

            entity.HasIndex(e => e.CategoriaId, "IX_Noticias_CategoriaId");

            entity.HasIndex(e => e.FechaPublicacion, "IX_Noticias_FechaPublicacion").IsDescending();

            entity.HasIndex(e => e.PaisId, "IX_Noticias_PaisId");

            entity.HasIndex(e => e.UsuarioId, "IX_Noticias_UsuarioId");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Contenido).IsRequired();
            entity.Property(e => e.FechaPublicacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ImagenUrl).HasMaxLength(500);
            entity.Property(e => e.Resumen).HasMaxLength(500);
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Categoria).WithMany(p => p.Noticia)
                .HasForeignKey(d => d.CategoriaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Noticias__Catego__48CFD27E");

            entity.HasOne(d => d.Pais).WithMany(p => p.Noticia)
                .HasForeignKey(d => d.PaisId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Noticias__PaisId__47DBAE45");

            entity.HasOne(d => d.Usuario).WithMany(p => p.Noticia)
                .HasForeignKey(d => d.UsuarioId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Noticias__Usuari__49C3F6B7");
        });

        modelBuilder.Entity<Paise>(entity =>
        {
            entity.HasKey(e => e.PaisId).HasName("PK__Paises__B501E1859CB60AD7");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.UsuarioId).HasName("PK__Usuarios__2B3DE7B811687739");

            entity.HasIndex(e => e.NombreUsuario, "UQ__Usuarios__6B0F5AE01FDDCEFF").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Usuarios__A9D10534C6306A8C").IsUnique();

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NombreCompleto)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NombreUsuario)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Rol)
                .IsRequired()
                .HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}