// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NoticiasAdmin.Models;

public partial class Noticia
{
    public int NoticiaId { get; set; }

    public string Titulo { get; set; }

    public string Contenido { get; set; }

    public string Resumen { get; set; }

    public string ImagenUrl { get; set; }

    public int PaisId { get; set; }

    public int CategoriaId { get; set; }

    public int UsuarioId { get; set; }

    public DateTime? FechaPublicacion { get; set; }

    public bool? Activo { get; set; }

    public virtual Categoria Categoria { get; set; }

    public virtual Paise Pais { get; set; }

    public virtual Usuario Usuario { get; set; }
}