// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NoticiasAdmin.Models;

public partial class Usuario
{
    public int UsuarioId { get; set; }

    public string NombreUsuario { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string NombreCompleto { get; set; }

    public string Rol { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public virtual ICollection<Noticia> Noticia { get; set; } = new List<Noticia>();
}