// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NoticiasAPI.Models;

public partial class Categoria
{
    public int CategoriaId { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public virtual ICollection<Noticia> Noticia { get; set; } = new List<Noticia>();
}